spring.application.name=controlefinanceiro
# Configurações de Conexão com o Banco de Dados
spring.datasource.url=jdbc:mysql://localhost:3306/controle_financeiro?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuração do JPA/Hibernate
# O valor 'validate' garante que o Java apenas verifique se as tabelas existem,
# sem tentar recriá-las e apagar seus dados.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Segredo do JWT (Em produção, isso deve ser uma variável de ambiente complexa)
api.security.token.secret=12345678